---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

DISABLE_LINTERS:
  - JAVA_CHECKSTYLE
  - REPOSITORY_CHECKOV

# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
DISABLE_ERRORS: true
YAML_FILTER_REGEX_EXCLUDE: ".github/workflows/mega-linter.yml"

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
